version: '3.8'
services:
  # Postgres service
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: loftwah
    ports:
      - "5433:5432"

  # Redis service
  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  # Rails service
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  # Resque worker service
  resque:
    build: .
    command: sh -c "QUEUE=* bundle exec rake resque:work"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  # Resque Scheduler service
  resque-scheduler:
    build: .
    command: bundle exec rake resque:scheduler
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
